### PR TITLE
docs: update news for 0.7.0 release

### PR DESCRIPTION
**Pull request by dshemetov**
Since `main` is already on 0.7.0 and it's stable-enough, we should make it a release. This updates the NEWS with a few bullets from the release notes generated by the current `main` branch. 

After we merge this, we can make a release 0.7.0, then bump the dev branch to 0.7.0.9000 (see Nat's comment in #383) and starting adding PR change lines under that heading.

### CODE REVIEW

**Comment by brookslogan** [comment]
That check failure's probably bad.  Think we need a version range on epidatr.

**Comment by dshemetov** [comment]
The check is failing because this doesn't have the ds/clean fixes in it, those are on dev.

**Comment by brookslogan** [comment]
Okay, 0.7.0 should actually include ds/clean then?

**Comment by dshemetov** [comment]
yea, doesn't seem worth trying to perfect 0.7.0. we should just try to get to a 0.8.0 release soon.

**Pull request merged**
