### PR TITLE
Djm/pkgdown prettier

### PR DESCRIPTION
**Pull request by dajmcdon**
Improve the pkgdown site (nice and red and matches `epipredict`).

Checks fail until #377 is merged.

### CODE REVIEW

**Comment by dajmcdon** [comment]
@brookslogan needs `ds/clean` to pass checks (at least).

**Comment by brookslogan** [comment]
I think we're still trying to decide on branch organization --- it appears that pkgdown lets you build main & dev documentation sites independently of how you organize your branches (instead basing it on whether you use a 3-number or 4-number version tag) --- but I believe we decided to try to standardize the appearance across both main & dev sites rather than maintain separate styles.  So I will try to merge this in.  One thing we need to check is whether there is some auto-differentiation of style by pkgdown using red text for dev version numbers that may not be visible against a red bar at the top.

**Comment by brookslogan** [comment]
Looks good, but before approving & merging, checking about provenance.  (Certain themes are exclusive to tidyverse or some other universe/org.)

**Review by brookslogan — APPROVED** [review]
Provenance: epipredict styling copied here was by @dajmcdon following https://pkgdown.r-lib.org/articles/customise.html.

**Comment by brookslogan** [comment]
Because `dev` currently has a 4-digit version number, merging this will likely only update the dev site... which appears not to have been built successfully yet; [the expected landing page](https://cmu-delphi.github.io/epiprocess/dev) gives a 404.  Maybe merging will give it a chance to build with the epidatr sync PR.

**Comment by brookslogan** [comment]
Oh, dev didn't exist because #383 wasn't finished yet.  No wonder there were no conflicts.

**Pull request merged**
