### PR TITLE
Remove default `n` values in `epi_slide` and `epix_slide`

### PR DESCRIPTION
**Pull request by kenmawer**
Addresses issue #160.

### CODE REVIEW

**Comment by brookslogan** [comment]
Code changes look good to go.  Doc changes look good, but see question below.  Interestingly, as far as I can tell, the vignettes are all already compatible with this change!

Question: is it worth clarifying in the @param n docs (for epi_slide, epix_slide, $slide) that `n` must be passed by name?

**Comment by brookslogan** [comment]
I don't think GitHub recognizes "addresses", but does recognize "closes" and "resolves".  Closes #160.

**Comment by kenmawer** [comment]
Note that I still haven't done `epix_slide` yet.

**Comment by kenmawer** [comment]
Note that this is for `epi_slide` only and not `epix_slide`.

**Comment by brookslogan** [comment]
In GitHub's diffs, I see changes in epi_slide, epix_slide, and epi_archive's $slide.  Are some of them not supposed to be there?

**Comment by kenmawer** [comment]
These should be here, because we are removing the default `n` values. Any changes in the documentation, etc. is due to taking out the now outdated info about the default `n` being 7 where it's specified.

**Comment by brookslogan** [comment]
Sorry, having trouble loading in context.

> Note that this is for `epi_slide` only and not `epix_slide`.

Could you please explain this a bit further?

**Comment by kenmawer** [comment]
My point was that I did not make changes relating to removing the default `n` value in `epix_slide`. However, I did these changes for `epi_slide`.

**Comment by brookslogan** [comment]
Note from call: removing the `n` default did apply to both epi slide and epix slide.  The change that didn't apply to both was in another PR.

**Pull request merged**
