### PR TITLE
Djm/as tibble attr

### LINKED ISSUE #467: Do we need `as_tibble()` to drop the class?
https://github.com/cmu-delphi/epiprocess/blob/7fd2119d5d116069297e06b70dbf3ff5c08c07bf/R/methods-epi_df.R#L11

* This makes epipredict internals painful. I can see that someone may want this behaviour, but it means any time someone calls a function (from another package) that _anywhere_ uses `as_tibble()`, it drops the class.

### PR DESCRIPTION
**Pull request by dajmcdon**
### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main" (unless this is a release
      PR).
- [x] Request a review from one of the current main reviewers:
      brookslogan, nmdefries.
- [x] Makes sure to bump the version number in `DESCRIPTION`. Always increment
      the patch version number (the third number), unless you are making a
      release PR from dev to main, in which case increment the minor version
      number (the second number).
- See [DEVELOPMENT.md](DEVELOPMENT.md) for more information on the development
  process.

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #467

### CODE REVIEW

**Review by brookslogan — APPROVED** [review]
Approach looks nice, we get to keep sane behavior for users that take it `as_tibble()` by its name.  I added a bit of roxygen, NEWS.md, and conditional attr printing to make it less mysterious.

Question: how do you want propagation for this attribute to work?  It looks like there is some amount of propagation already, e.g., surviving through `mutate()`, but it does not survive via `|> group_by(geo_value) |> ungroup()` (unlike our metadata).  (And there are still other cases (e.g., #250) where our metadata / `epi_df`ness doesn't survive when we'd want it to.)  If you want it to be hardier, then it probably belongs within `metadata` + a double-check of whether `reclass()` and `dplyr_reconstruct.epi_df()` do indeed propagate it then.

**Comment by dajmcdon** [comment]
My thinking on grouping: since `as_tibble(regular_tibble)` drops the grouping, this should as well for now. I wanted the the deviations from expected behaviour to be as minimal as possible while being sufficient for my needs. I suppose an external user *could* want this functionality, but providing it seems likely to be very low on the pile of issues until someone asks.

**Comment by brookslogan** [comment]
I didn't mean that we shouldn't drop the grouping with `as_tibble()`.  I meant that grouping & ungrouping (and likely various other operations) drops the `decay_to_tibble` attribute.

**Comment by dajmcdon** [comment]
Oh, I see. Yes, I'm hopeful that there's no grouping on internally that will screw me up. But good to have a record here in case it does!

**Pull request merged**
