### PR TITLE
refactor: remove Suggests dependence on covidcast

### PR DESCRIPTION
**Pull request by dshemetov**
### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main" (unless this is a release
      PR).
- [x] Request a review from one of the current main reviewers:
      brookslogan, nmdefries.
- [ ] Makes sure to bump the version number in `DESCRIPTION`. Always increment
      the patch version number (the third number), unless you are making a
      release PR from dev to main, in which case increment the minor version
      number (the second number).
- [ ] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      1.7.2, then write your changes under the 1.8 heading).
- See [DEVELOPMENT.md](DEVELOPMENT.md) for more information on the development
  process.

### Change explanations for reviewer

* just download the files, don't import covidcast
* covidcast depends on sf which is tough to install (it just refuses to compile on my machine) and my renv keeps trying to install ALL dependencies

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #{issue number}

### CODE REVIEW

**Comment by brookslogan** [comment]
I think we can do this more simply with a small addition to #520.  Reviewing #520 now and going to try out.

**Comment by dshemetov** [comment]
Makes sense. Should probably be solved upstream in this case https://github.com/cmu-delphi/epidatasets/issues/7

**Comment by brookslogan** [comment]
`state_census` at least is already there... but I guess `county_census` is not.  Unfortunate, would require upstream work I guess.

**Comment by dshemetov** [comment]
It's basically a one line change to the epidatasets scripts, it's not bad

**Review by brookslogan — APPROVED** [review]
Think this is good to go.  Going to force-push to try to make some checks happen.

**Pull request merged**
