### PR TITLE
Fix & improve .window_size validation

### PR DESCRIPTION
**Pull request by brookslogan**
### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main" (unless this is a release
      PR).
- [-] Request a review from one of the current main reviewers:
      brookslogan, nmdefries.
- [x] Makes sure to bump the version number in `DESCRIPTION`. Always increment
      the patch version number (the third number), unless you are making a
      release PR from dev to main, in which case increment the minor version
      number (the second number).
- [x] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      1.7.2, then write your changes under the 1.8 heading).
  - (going to merge others first & figure out right number)
- See [DEVELOPMENT.md](DEVELOPMENT.md) for more information on the development
  process.

### Change explanations for reviewer

- Fixes where time_type = "day" would allow any type of difftime.
- Complete docs and match code&messages wrt .window_size validation
  * Mention what's acceptable for yearmonth time_type
  * Mention Inf in validation errors as acceptable iff it's actually acceptable.
  * Reject any other strange "int" classes that pass test_int. (It rejects Date
  and POSIXt, but perhaps there are others.)
  * Refactor to use helper function test_sensible_int instead of test_int (as
  latter accepts difftimes and makes logic look confusing).- 

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #{issue number}

### CODE REVIEW

**Review by dshemetov — COMMENTED** [review]
Ah, I'm seeing a bunch of minor improvements to the slide args I didn't move over to epi_slide_opt, I can add a commit in a little. Thanks for noticing!

**Comment by brookslogan** [comment]
Will you be removing .window_size = 1 default as part of the epi_slide_opt sync?  I was originally setting out to do that and got distracted, oops.

**Comment by dshemetov** [comment]
Yea I didn't port the validation from epi_slide over epi_slide_opt, but I'll do that now.

**Review by dshemetov — APPROVED** [review]
Ok looks better now. Should be good to go.

**Pull request merged**
